# Configura��o do Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yml

# Configura��o do Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/board
spring.datasource.username=developer
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
